default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: commerce_app_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: commerce_app_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: commerce_app_production
  username: commerce_app
  password: <%= ENV["COMMERCE_APP_DATABASE_PASSWORD"] %>
